name: yurttaye_mobile
description: A Flutter app to view YurttaYe menus
version: 1.4.0+28

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.0
  http: ^1.0.0
  intl: ^0.20.2
  go_router: ^14.0.0
  google_fonts: ^6.0.0
  shimmer: ^3.0.0
  shared_preferences: ^2.0.0
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_iconly: ^1.0.2
  url_launcher: ^6.3.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.2
  google_mobile_ads:
  flutter_dotenv: ^5.1.0
  permission_handler: ^11.3.0
  share_plus: ^10.1.4
  screenshot: ^3.0.0
  path_provider: ^2.1.4

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - .env